### ISSUE TITLE
Update ERD

### ISSUE THREAD

**Issue by jackthepanda96** [nurulalyh/PharmStock-MiniProject#30]
Coba jelaskan sedikit di bagian detail_products

apa garisnya ga kebalik?

**Comment by nurulalyh** [comment]
Dari sepahaman saya mas, jadi detail_product ini punya relasi ke 3 entitas. kalau detail_products ke transaction, berarti satu detail_products punya banyak riwayat transaksi. Lalu product ke detail_product, berarti satu product punya banyak detail_product karena nomor batch yang berbeda-beda. Terakhir distributor ke detail_product, berarti satu distributor punya beberapa produk yang di pasok ke apotek. Apa ada yang kebalik mas?
